// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn9tDMnmojpLzaDLT1xnJQR060DPG8mJ0',
    appId: '1:352645584006:web:1ae2c73b2fad57442e6d07',
    messagingSenderId: '352645584006',
    projectId: 'poauk-f8ba2',
    authDomain: 'poauk-f8ba2.firebaseapp.com',
    storageBucket: 'poauk-f8ba2.appspot.com',
    measurementId: 'G-QGFH4PYC3H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqdOKcgAOd4c5wB0BPDP6hyp8m7IiZN7M',
    appId: '1:352645584006:android:b14fd329f86b01372e6d07',
    messagingSenderId: '352645584006',
    projectId: 'poauk-f8ba2',
    storageBucket: 'poauk-f8ba2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhZjxRcd_eVq4NhGPysgTO11wDTHjqDro',
    appId: '1:352645584006:ios:b83df56c88d93ec42e6d07',
    messagingSenderId: '352645584006',
    projectId: 'poauk-f8ba2',
    storageBucket: 'poauk-f8ba2.appspot.com',
    iosClientId: '352645584006-r8gfnh2gb4djftnbl7ld27097ro7uf14.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAcademy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhZjxRcd_eVq4NhGPysgTO11wDTHjqDro',
    appId: '1:352645584006:ios:42a11db199f671c12e6d07',
    messagingSenderId: '352645584006',
    projectId: 'poauk-f8ba2',
    storageBucket: 'poauk-f8ba2.appspot.com',
    iosClientId: '352645584006-jkvl8hc8snfoff2fj6j6p6a6h1l3cjo0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAcademy.RunnerTests',
  );
}
